version: '2.3'
services:
  wrapper:
    build:
      context: .
    network_mode: "host"
    environment:
    - RUST_LOG=info
    - TEST_POOL_IP=$TEST_POOL_IP
    - DEPLOY=${DEPLOY:-false}
    volumes:
      - $HOME/.m2/settings.xml:/root/.m2/settings.xml
  pool:
    image: studybits/indy-pool:local
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"